Repository eclipse/gemoc-studio-execution-ale, pull requests merged in 2019-06, with the labels that each got.

#15 Update icons to official branding colors
  examples/language_workbench/org.eclipse.gemoc.sample.ale.fsm.model/.project
  plugins/org.eclipse.gemoc.ale.interpreted.engine.ui/icons/gemoc-model-ale-icon-16.png
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/.gitignore
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/icons/ALE.gif
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/icons/gemoc-model-ale-icon-16.png
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/icons/language-16.png
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/plugin.xml
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/zips/org.eclipse.gemoc.sample.ale.fsm.design.zip
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/zips/org.eclipse.gemoc.sample.ale.fsm.model.zip
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/zips/org.eclipse.gemoc.sample.ale.fsm.model_examples.zip
  plugins/org.eclipse.gemoc.ale.language.sample.deployer/zips/org.eclipse.gemoc.sample.ale.xfsm.design.zip
Labels: releng

#19 Bump ALE version to 2019-06-24
  docs/dev/ALEExecution.asciidoc
  pom.xml
Labels: bump

#16 Fix issue #13
  plugins/org.eclipse.gemoc.ale.interpreted.engine.ui/src/org/eclipse/gemoc/ale/interpreted/engine/ui/launcher/tabs/LaunchConfigurationMainTab.java
  plugins/org.eclipse.gemoc.ale.interpreted.engine/src/org/eclipse/gemoc/ale/interpreted/engine/Helper.java
Labels: bug

#18 Fix: print error log for model executions
  plugins/org.eclipse.gemoc.ale.interpreted.engine/src/org/eclipse/gemoc/ale/interpreted/engine/AleEngine.java
Labels: bug
